---
title: "Analysis of MDD GWAS Progress over time "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## SETUP
First set up required libraries
```{r echo=FALSE}
library("tidyverse")
library("readxl")
require("ggrepel")
require("scales")
```

## READ DATA from Excel Spreadsheet
```{r echo=TRUE}
gwasMDD <- read_excel(path = "MDD-GWAS.xlsx" ) %>%
print()
```

## Including Plots
Plot MDD GWAS NHits over time
```{r echo = FALSE}
p <- ggplot(gwasMDD, aes(x = Ncases, y = Nhits, label = fauthor)) +
  theme(panel.background = element_rect(fill="white", 
                                        color="white", 
                                        linetype="solid"), 
        panel.grid.major.y = element_line(colour = "grey"), 
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()  ) +
  
  scale_x_continuous(labels = label_number(suffix = "K", 
                                           scale = 1e-3)) +

  geom_point() +
  
  geom_smooth(method = "loess", formula = (y~x), se=FALSE) +
  
  geom_label_repel(min.segment.length = 0.5,
                   max.overlaps = Inf,
                   label.size=0,
                   label.padding=0.2,
                   label.r=0.2,
                   size=3) +
  
coord_cartesian(xlim=c(0,500000), ylim=c(-10, 520)) +
  
labs(title = "MDD GWAS Progress with Increasing Case Numbers",
     subtitle=NULL,
     x="Number of Depressed Cases",
     y="Number of Significant Loci") 

print(p)
ggsave("Hits.jpeg", plot = p)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
